# Generated by Django 3.1.5 on 2021-02-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
