# Generated by Django 3.1.5 on 2021-02-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210222_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='classAdded',
            field=models.CharField(default='claseaañadir', max_length=200, verbose_name='Clase añadida'),
        ),
    ]
