# Generated by Django 3.1.5 on 2021-02-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_classadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preview',
            field=models.ImageField(default=0, upload_to='services', verbose_name='Preview'),
        ),
    ]
