# Generated by Django 3.1.5 on 2021-03-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='preview',
        ),
    ]
