# Generated by Django 3.1.5 on 2021-02-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210222_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
