# Generated by Django 3.1.5 on 2021-02-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210222_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title',), 'verbose_name': 'entrada', 'verbose_name_plural': 'entradas'},
        ),
    ]
