# Generated by Django 3.1.5 on 2021-02-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210223_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
    ]
