# Generated by Django 3.1.5 on 2021-02-22 10:43

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_studies_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studies',
            name='image',
        ),
        migrations.AddField(
            model_name='studies',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='video', verbose_name='Vídeo'),
        ),
    ]
