# Generated by Django 3.1.5 on 2021-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20210222_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studies',
            name='video',
            field=models.FileField(upload_to='studies', verbose_name='Vídeo'),
        ),
    ]
