# Generated by Django 3.1.5 on 2021-03-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20210222_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='studies',
            name='preview',
            field=models.ImageField(default=0, upload_to='services', verbose_name='Preview'),
        ),
    ]
